---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployments-app-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployments-app-web
  template:
    metadata:
      labels:
        app: deployments-app-web
    spec:
      containers:
        - name: app-web
          image: angeliney/catnip:latest
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: deployments-app-web
  labels:
    app: deployments-app-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: deployments-app-web