name: module-2/test-minio-client

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - main
    paths:
      - 'module-2/minio-python-client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./module-2/minio-python-client
    steps:
      - uses: actions/checkout@v4
      -   
        name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
      - 
        name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Run docker image in the background
        run: |
            nohup docker run -d -p 9000:9000 ${{ vars.DOCKERHUB_USERNAME }}/minio-docker:latest> my.log 2>&1 &
      -
        name: Run tests
        run: |
            pytest .
      
