name: module-2/build-minio-docker

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - main
    paths:
      - 'module-2/minio-docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: "{{defaultContext}}:module-2/minio-docker"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/minio-docker:latest
